language : node_js
sudo: required
services:
  - 'docker'

node_js :
 - stable
 - node
 - '9'

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install

script:
  - yarn lint

before_deploy:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag $IMAGE_NAME $DOCKER_USERNAME/${IMAGE_NAME}:latest
  - docker tag $IMAGE_NAME $DOCKER_USERNAME/${IMAGE_NAME}:${version}

deploy:
  provider: script
  script:
    - docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master